INSERT INTO errors (name, code) VALUES ('Bad Request', 400);
INSERT INTO errors (name, code) VALUES ('Unauthorized', 401);
INSERT INTO errors (name, code) VALUES ('Forbidden', 403);
INSERT INTO errors (name, code) VALUES ('Not Found', 404);
INSERT INTO errors (name, code) VALUES ('Method Not Allowed', 405);
INSERT INTO errors (name, code) VALUES ('Not Acceptable', 406);
INSERT INTO errors (name, code) VALUES ('Proxy Authentication Required', 407);
INSERT INTO errors (name, code) VALUES ('Request Timeout', 408);
INSERT INTO errors (name, code) VALUES ('Conflict', 409);
INSERT INTO errors (name, code) VALUES ('Gone', 410);
INSERT INTO errors (name, code) VALUES ('Length Required', 411);
INSERT INTO errors (name, code) VALUES ('Precondition Failed', 412);
INSERT INTO errors (name, code) VALUES ('Payload Too Large', 413);
INSERT INTO errors (name, code) VALUES ('URI Too Long', 414);
INSERT INTO errors (name, code) VALUES ('Unsupported Media Type', 415);
INSERT INTO errors (name, code) VALUES ('Range Not Satisfiable', 416);
INSERT INTO errors (name, code) VALUES ('Expectation Failed', 417);
INSERT INTO errors (name, code) VALUES ('Misdirected Request', 421);
INSERT INTO errors (name, code) VALUES ('Unprocessable Entity', 422);
INSERT INTO errors (name, code) VALUES ('Locked', 423);
INSERT INTO errors (name, code) VALUES ('Failed Dependency', 424);
INSERT INTO errors (name, code) VALUES ('Too Early', 425);
INSERT INTO errors (name, code) VALUES ('Upgrade Required', 426);
INSERT INTO errors (name, code) VALUES ('Precondition Required', 428);
INSERT INTO errors (name, code) VALUES ('Too Many Requests', 429);
INSERT INTO errors (name, code) VALUES ('Request Header Fields Too Large', 431);
INSERT INTO errors (name, code) VALUES ('Unavailable For Legal Reasons', 451);
